LibraryRequiem/Controllers/CollectionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using LibraryRequiem.Data;
using LibraryRequiem.Models;
using Microsoft.AspNetCore.Mvc.Filters;
using System.Xml;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using static System.Collections.Specialized.BitVector32;
using Microsoft.Identity.Client;
using System.Xml.XPath;
using System.Security.Cryptography.Pkcs;
using Microsoft.AspNetCore.Authorization;
using LibraryRequiem.Models.ViewModel;
using static System.Reflection.Metadata.BlobBuilder;

namespace LibraryRequiem.Controllers
{
    public class CollectionController : Controller
    {
        //Создание переменных для информации об окружении веб-приложения и контекста базы данных
        private readonly CollectionContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IDbContextFactory<CollectionContext> _dbContextFactory;

        //Инициализация этих переменных
        public CollectionController(CollectionContext context, IWebHostEnvironment webHostEnvironment, IDbContextFactory<CollectionContext> dbContextFactory)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            _dbContextFactory = dbContextFactory;
        }

        //Переопределение метода OnActionExecuting
        public override void OnActionExecuting(ActionExecutingContext context)
        {
            //Помещение всех полей Genre из базы данных в переменную Genres
            IEnumerable<string> Genres = _context.Books.Select(g => g.Genre);

            //Исключение повторяющихся элементов
            Genres = Genres.Distinct();

            //Помещение Genres во ViewBag
            ViewBag.Genres = Genres;

            //Сохранение изменений
            base.OnActionExecuting(context);
        }

        // GET: Collection
        public async Task<IActionResult> Index()
        {
            var books = await _context.Books.ToListAsync();
            var viewModel = new CollectionIndexViewModel();

            if (User.Identity.IsAuthenticated)
            {
                using(var context = _dbContextFactory.CreateDbContext())
                {
                    UserModel user = new UserModel();

                    user = await context.Users.Include(x => x.FavoriteList.Books)
                .FirstOrDefaultAsync(x => x.UserName == User.Identity.Name);

                    viewModel.User = user;
                    viewModel.Books = books;

                }

                return View(viewModel);
            }

            viewModel.User = null;
            viewModel.Books = books;
            //Возврат объектов бд в виде списка
            return _context.Books != null ? 
                          View(viewModel) :
                          Problem("Entity set 'CollectionContext.Books'  is null.");
        }

        //GET collection/Download/5
        public async Task<IActionResult> Download(int? id)
        {
            //Проверка на null и возврат NotFound
            if (id == null || _context.Books == null)
            {
                return NotFound();
            }
            try
            {
                //Проверка id и бд на null и возврат NotFound
                var bookModel = await _context.Books.AsNoTracking().FirstOrDefaultAsync(x => x.Id == id);

                //Создание пути к загружакмому файлу
                var pathToDownload = Path.GetFullPath($@"{_webHostEnvironment.WebRootPath}{bookModel.BookFilePath}");

                //Преобразование файла в массив байтов
                byte[] fileBytes = System.IO.File.ReadAllBytes(pathToDownload);

                //Получение имени файла
                string fileName = pathToDownload;
                fileName = Path.GetFileName(fileName);

                return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
            }
            catch { return NotFound(); }
        }

        //GET:
        public async Task<IActionResult> SearchResult(string? searchitem, string? searchGenre)
        {
            var books = _context.Books.AsNoTracking();
            var viewModel = new CollectionIndexViewModel();

            //Проверка поля поискового запроса на null
            if (searchitem != null)
            {
                //Фильтрация объектов бд и помещение в searchResult
                var searchResult = books.Where(p => EF.Functions.Like(p.Title, $"%{searchitem}%") || EF.Functions.Like(p.Author, $"%{searchitem}%")).ToListAsync();

                ViewBag.Search = $"Поиск по запросу: {searchitem}";

                ViewBag.SearchField = searchitem;

                if (User.Identity.IsAuthenticated)
                {
                    using (var context = _dbContextFactory.CreateDbContext())
                    {
                        UserModel user = new UserModel();

                        user = await context.Users.Include(x => x.FavoriteList.Books)
                    .FirstOrDefaultAsync(x => x.UserName == User.Identity.Name);

                        viewModel.User = user;
                        viewModel.Books = await searchResult;

                    }

                    return View(viewModel);
                }

                viewModel.User = null;
                viewModel.Books = await searchResult;

                return View(viewModel);
            }

            //Проверка поля поискового запроса на null
            else if (searchGenre != null)
            {
                //Фильтрация объектов бд и помещение в searchResult
                var searchResult = books.Where(p => EF.Functions.Like(p.Genre, $"%{searchGenre}%")).ToListAsync();

                ViewBag.Search = $"Книги жанра: {searchGenre}";

                if (User.Identity.IsAuthenticated)
                {
                    using (var context = _dbContextFactory.CreateDbContext())
                    {
                        UserModel user = new UserModel();

                        user = await context.Users.Include(x => x.FavoriteList.Books)
                    .FirstOrDefaultAsync(x => x.UserName == User.Identity.Name);

                        viewModel.User = user;
                        viewModel.Books = await searchResult;

                    }

                    return View(viewModel);
                }

                viewModel.User = null;
                viewModel.Books = await searchResult;

                return View(viewModel);
            }

            return View();
        }

        // GET: Collection/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            //Проверка id и бд на null и возврат NotFound
            if (id == null || _context.Books == null)
            {
                return NotFound();
            }

            //Поиск объекта бд по его id
            var bookModel = await _context.Books.FindAsync(id);

            if (bookModel == null)
            {
                return NotFound();
            }

            return View(bookModel);
        }

        // GET: Collection/Create


        [Authorize]
        [AllowAnonymous]
        public IActionResult Create()
        {
            if (!User.IsInRole("admin"))
            {
                ModelState.AddModelError("", "Вы не админ!!!");
                return PartialView("../Accounts/login");
            };

            return View();
        }

        // POST: Collection/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [ValidateAntiForgeryToken]
        [RequestFormLimits(MultipartBodyLengthLimit = int.MaxValue)]
        [RequestSizeLimit(int.MaxValue)]
        [HttpPost]
        [Authorize]
        [AllowAnonymous]
        public async Task<IActionResult> Create(IFormFile bookImage, IFormFile bookFile, [Bind("Id,Title,Author,Genre,Description,DateOfUpload,Tags")] BookModel bookModel)
        {
            // Создание путей к обложке книги и ее файлу
            bookModel.BookFilePath = @$"/Files/Book{bookModel.Id}/{bookFile.FileName}";
            bookModel.BookImagePath = @$"/Files/Book{bookModel.Id}/{bookImage.FileName}";

            // Добавление модели в базу данных
            _context.Add(bookModel);
            await _context.SaveChangesAsync();

            // Создание путей в файловой системе для обложки книги и ее файла
            var pathToSaveImage = Path.GetFullPath(@$".\wwwroot\Files\Book{bookModel.Id}\{bookImage.FileName}");
            var pathToSaveFile = Path.GetFullPath($@".\wwwroot\Files\Book{bookModel.Id}\{bookFile.FileName}");

            // Заполнение полей модели значениями
            bookModel.BookFilePath = @$"/Files/Book{bookModel.Id}/{bookFile.FileName}";
            bookModel.BookImagePath = @$"/Files/Book{bookModel.Id}/{bookImage.FileName}";
            bookModel.Id = bookModel.Id;
            bookModel.DateOfUpload = DateTime.Now;

            // Проверка формата файла книги
            if (Path.GetExtension(bookFile.FileName) != ".fb2" && Path.GetExtension(pathToSaveFile) != ".fb2")
            {
                ModelState.AddModelError("BookFilePath", "Неверный формат книги");
            }

            // Проверка формата обложки книги
            if (Path.GetExtension(bookImage.FileName) != ".jpg" && Path.GetExtension(pathToSaveImage) != ".png")
            {
                ModelState.AddModelError("BookImagePath", "Неверный формат изображения");
            }

            // Получение информации о директории
            DirectoryInfo directoryInfo = new DirectoryInfo($@"{_webHostEnvironment.WebRootPath}\Files\Book{bookModel.Id}\");

LibraryRequiem/Views/Collection/Create.cshtml
<!-- Передаем в представление объект BookModel -->
@model LibraryRequiem.Models.BookModel

@{
    <!-- Описываем заголовок отображаемый в окне браузера -->
    ViewData["Title"] = "Добавить книгу";
}
<!-- Контейнер страницы -->
<div class="create_container">
    <h2>Добавить книгу в коллекцию</h2>
    <hr />
    <!-- Использование класса row системы BootsTrap, который позволяет создать горизонтальный ряд с колонками -->
    <div class="row">
        <!-- Использование класса col-md-auto системы BootsTrap, который  указывает, что элемент будет занимать несколько колонок в широком экране (md) -->
        <div class="col-md-auto">
            <form asp-action="Create" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <!-- Получение имени свойства Title модели BookModel -->
                    <label asp-for="Title"></label>
                    <!-- Значение этого input будут присвоены модели, его свойству Title-->
                    <input asp-for="Title"/>
                    <!-- При неверном заполнении формы отображает ошибку связанную с этим свойством -->
                    <span asp-validation-for="Title"/>
                </div>
                <div class="form-group">
                    <label asp-for="Author"></label>
                    <input asp-for="Author" />
                    <span asp-validation-for="Author" />
                </div>
                <div class="form-group">
                    <label asp-for="Genre"></label>
                    <input asp-for="Genre" />
                    <span asp-validation-for="Genre" />
                </div>
                <div class="form-group">
                    <label asp-for="Description"></label>
                    <input asp-for="Description" />
                    <span asp-validation-for="Description" />
                </div>
                <div class="form-group">
                    <label asp-for="Tags"></label>
                    <input asp-for="Tags" />
                    <span asp-validation-for="Tags" />
                </div>
                <div class="form-group">
                    <!-- Получение имени свойства BookModel модели BookModel -->
                    <label asp-for="BookImagePath"></label>
                    <!-- Через это поле пользователи могут выбрать файлы для отправки на сервер, с именем элемента ввода bookImage -->
                    <input type="file" name="bookImage" required />
                    <!-- При неверном заполнении формы отображает ошибку связанную со свойством BookImagePath-->
                    <span asp-validation-for="BookImagePath" />
                </div>
                <div class="form-group">
                    <label asp-for="BookFilePath"></label>
                    <input type="file" name="bookFile" required />
                    <span asp-validation-for="BookFilePath" />
                </div>
                <div class="form-group">
                    <!-- Кнопка при нажатии на которую введенные данные отправятся на сервер, btn bnt-primary - класс bootstrap для выделения кнопки  -->
                    <input type="submit" value="Сохранить" class="btn btn-primary" />
                </div>
                <div class="form-group">
                    <a asp-action="Index">Back to List</a>
                </div>
            </form>
        </div>
    </div>
</div>

LibraryRequiem/Views/Collection/Details.cshtml
<!-- Передаем в представление объект BookModel -->
@model LibraryRequiem.Models.BookModel

@{
    <!-- Описываем заголовок отображаемый в окне браузера -->
    ViewData["Title"] = @Model.Title;
}
<!-- Контейнер страницы -->
<div class="detail_container">
    <!-- Контейнер левой части страницы -->
    <div class="details_left">
        <div class="image">
            <!-- Обращение к модели страницы для получения пути к обложке -->
            <img class="details_image" src="@Model.BookImagePath"/>
            <!-- Кнопка редактирования книги, передает в контроллер Edit id книги и перенаправляет пользователя на страницу редактирования  книги -->
            <form method="get">
                <button class="edit_button" type="submit" class="details_edil" asp-route-id="@Model.Id" asp-action="Edit" value="Редактировать">
                    <img class="edit_icon" src="~/images/675757_edit_512x512.png"/>
                </button>
            </form>
        </div>
        <form method="get">
        <ul class="detail_info">
            <oi class="detail_download">
                <!-- Кнопка скачивания, передаёт в метод Download Id книги -->
                <button type="submit" class="detail_download_button" asp-route-id="@Model.Id" asp-action="Download">Скачать</button>
            </oi>
            <oi class="author_detail">
                <!-- В Post запросе в действие SearchResult передается имя автора, при нажатии на него -->
                <button type="submit" class="detail_author_button" value="@Model.Author" name="searchitem" asp-action="SearchResult">Автор: @Model.Author</button>
            </oi>
            <oi class="detail_date">
                <label>Дата загрузки:</label>
                <!-- Обращение к полю DateOfUpload модели BookModel для получения даты загрузки -->
                <a style="text-decoration: none; color: black;">@Model.DateOfUpload</a>
            </oi>
        </ul>
        </form>
    </div>
    <!-- Контейнер правой части страницы -->
    <div class="detail_right">
        <div class="detail_name">
            <!-- Обращение к полю Title модели BookModel для получения названия книги -->
            <h2 class="detail_name_main">@Model.Title</h2>
        </div>
        <div class="description_with_tags">
            <div class="detail_description_tab">
                <h3 class="detail_description_tab_text">Описание</h3>
            </div>
            <div class="detail_description_content">
                <!-- Обращение к полю Description модели BookModel для получения опсания книгии -->
                <div class="detail_description_text">@Model.Description</div>
            </div>
            <ul class="detail_tags">
                <!-- Обращение к полю Tags модели BookModel для получения тегов книги -->
                <li class="detail_tag">@Model.Tags</li>
            </ul>
        </div>
    </div>
</div>

LibraryRequiem/Views/Collection/Edit.cshtml
<!-- Передаем в представление объект BookModel -->
@model LibraryRequiem.Models.BookModel

@{
    <!-- Описываем заголовок отображаемый в окне браузера -->
    ViewData["Title"] = $"{Model.Title} - редактирование";
}
<!-- Так как формы редактирования и добавления книг похожи используется тот же контейнер -->
<div class="create_container">
    <h2>@Model.Title - Редактирование</h2>
    <hr />
    <div class="row">
        <div class="col-md-auto">
            <!-- Атрибут enctype формах определяет способ кодирования значение multipart/form-data используется когда форма отправляет файлы или большие объемы данных -->
            <form asp-action="Edit" method="post" enctype="multipart/form-data">
                <!-- Данный фрагмент используется для вывода сообщений об ошибках валидации модели на веб-странице -->
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <!-- На сервер отправляется id модели -->
                <input type="hidden" asp-for="Id" />
                <!-- На сервер отправляется свойство BookFilePath -->
                <input type="hidden" asp-for="BookFilePath" />
                <!-- На сервер отправляется свойство BookImagePath -->
                <input type="hidden" asp-for="BookImagePath" />
                <div class="form-group">
                    <label asp-for="Title" class="control-label"></label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Author" class="controll-label"></label>
                    <input asp-for="Author" class="form-controll"/>
                    <span asp-validation-for="Author" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Genre" class="control-label"></label>
                    <input asp-for="Genre" class="form-control" />
                    <span asp-validation-for="Genre" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DateOfUpload" class="control-label"></label>
                    <input asp-for="DateOfUpload" class="form-control" />
                    <span asp-validation-for="DateOfUpload" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Tags" class="control-label"></label>
                    <input asp-for="Tags" class="form-control" />
                    <span asp-validation-for="Tags" class="text-danger"></span>
                </div>
                    <div class="form-group">
                        <label asp-for="BookImagePath" class="control-label"></label>
                        <input type="file" name="bookImage" required/>
                        <span asp-validation-for="BookImagePath" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="BookFilePath" class="control-label"></label>
                        <input type="file" name="bookFile" required/>
                        <span asp-validation-for="BookFilePath" class="text-danger"></span>
                    </div>
                <div class="form-group">
                    <input asp-action="Edit" type="submit" value="Сохранить" class="btn btn-primary" />
                </div>
            </form>
            <form method="post">
            <div class="form-group">
                <!-- Кнопка запускает деействие Delete и передает в него id книги -->
                <button asp-action="Delete" asp-route-id="@Model.Id">Удалить</button>
            </div>
            </form>
            <div>
                <a asp-action="Index">Back to List</a>
            </div>
        </div>
    </div>
</div>

LibraryRequiem/Views/Collection/Index.cshtml
<!-- Передаем в представление коллекцию объектов BookModel -->
@model LibraryRequiem.Models.ViewModel.CollectionIndexViewModel

@{
    <!-- Описываем заголовок отображаемый в окне браузера -->
    ViewData["Title"] = "Коллекция";
}
<!-- Контейнер страницы -->
<div class="collection_container">
    <!-- Кнопка перенаправляющая пользователя на сраницу создания книги, действие Create -->
    @if (User.IsInRole("admin"))
    {
        <button class="create_button">
            <a asp-action="Create" asp-controller="Collection" class="create">
                Добавить
            </a>
        </button>
    }
    <!-- Ссылка на сайт где можно скачать программу для чтения -->
    <label class="calibre_label">Скачать программу для чтения <a class="calibre_href" href="https://calibre-ebook.com/ru/download_windows"> "Calibre" </a> с оффициального сайта</label>
    <!-- Сетка с картами книг -->
    <div class="cards">
        <!-- Перебор каждого экземпляра книги в модели -->
        @if (Model != null)
        {
            foreach (var item in Model.Books)
            {
                <!-- Карта книги -->
                <div class="card">
                    <div class="card_top">
                        <!-- Задается действие перехода на страницу с информацией о книге, при клике на её изображение -->
                        <a class="card_image" asp-action="Details" asp-controller="Collection" asp-route-id="@item.Id"><img src="@item.BookImagePath"></a>
                    </div>
                    <div class="card_bottom">
                        <!-- Задается действие перехода на страницу с информацией о книге, при клике на название -->
                        <a class="card_title" asp-action="Details" asp-controller="Collection" asp-route-id="@item.Id">@item.Title</a>
                        <div class="buttons">
                            <form class="author" method="post" asp-action="SearchResult" asp-controller="Collection">
                                <!-- В Post запросе в действие SearchResult передается имя автора, при нажатии на него -->
                                <button class="author_text" value="@item.Author" name="searchitem">@item.Author</button>
                            </form>
                            <!-- Задается действие перехода на страницу с информацией о книге, при клике на кнопку -->
                            <button class="detail-button">
                                <a class="text" asp-action="Details" asp-controller="Collection" asp-route-id="@item.Id">Подробнее</a>
                            </button>
                            <!-- Кнопка скачивания, передаёт в метод Download Id книги -->
                            <button class="download-button">
                                <a class="text" asp-action="Download" asp-controller="Collection" asp-route-id="@item.Id">Скачать</a>
                            </button>
                            <button class="read-button">
                                <a class="text" asp-action="ReadPage" asp-controller="Collection" asp-route-id="@item.Id">Читать</a>
                            </button>
                            @if (Model.User != null)
                            {
                                <button type="submit" class="read-button">
                                    <a class="text" href="/FavoriteList/AddTitle?id=@item.Id&currentPage=@Context.Request.HttpContext.Request.Path">В избранное</a>
                                </button>
                            }
                        </div>

                    </div>
                </div>
            }
        }
    </div>
</div>

LibraryRequiem/Views/Collection/ReadPage.cshtml
@{
    <!-- Описываем заголовок отображаемый в окне браузера -->
    ViewData["Title"] = "Читать";
}

<style> </style>
<div class="book">
    @if (ViewBag.Book != null)
    {
        @foreach(var paragraph in ViewBag.Book)
        {
            @Html.Raw(paragraph.ToString());
        }
    }
</div>

LibraryRequiem/Views/Collection/SearchResult.cshtml
<!-- Передаем в представление коллекцию объектов BookModel -->
@model LibraryRequiem.Models.ViewModel.CollectionIndexViewModel

@{
    <!-- Описываем заголовок отображаемый в окне браузера -->
    ViewData["Title"] = ViewBag.Search;

}
<!-- Контейнер страницы -->
<div class="search_container">
    <!-- Проверка модели на null, если её не провести то приложение остановится с исключением NullReferencesExpection -->
    @if(Model != null)
    {
        <!-- Отображение значения строки поиска в заголовке -->
        <h3 class="search_item">@ViewBag.Search</h3>
        <!-- Сетка с картами книг -->
        <div class="cards">
            <!-- Перебор каждого экземпляра книги в модели -->
            @if (Model != null)
            {
                foreach (var item in Model.Books)
                {
                    <!-- Карта книги -->
                    <div class="card">
                        <div class="card_top">
                            <!-- Задается действие перехода на страницу с информацией о книге, при клике на её изображение -->
                            <a class="card_image" asp-action="Details" asp-controller="Collection" asp-route-id="@item.Id"><img src="@item.BookImagePath"></a>
                        </div>
                        <div class="card_bottom">
                            <!-- Задается действие перехода на страницу с информацией о книге, при клике на название -->
                            <a class="card_title" asp-action="Details" asp-controller="Collection" asp-route-id="@item.Id">@item.Title</a>
                            <div class="buttons">
                                <form class="author" method="post" asp-action="SearchResult" asp-controller="Collection">
                                    <!-- В Post запросе в действие SearchResult передается имя автора, при нажатии на него -->
                                    <button class="author_text" value="@item.Author" name="searchitem">@item.Author</button>
                                </form>
                                <!-- Задается действие перехода на страницу с информацией о книге, при клике на кнопку -->
                                <button class="detail-button">
                                    <a class="text" asp-action="Details" asp-controller="Collection" asp-route-id="@item.Id">Подробнее</a>
                                </button>
                                <!-- Кнопка скачивания, передаёт в метод Download Id книги -->
                                <button class="download-button">
                                    <a class="text" asp-action="Download" asp-controller="Collection" asp-route-id="@item.Id">Скачать</a>
                                </button>
                                <button class="read-button">
                                    <a class="text" asp-action="ReadPage" asp-controller="Collection" asp-route-id="@item.Id">Читать</a>
                                </button>
                                @if (Model.User != null)
                                {
                                    <button type="submit" class="read-button">
                                        <a class="text" href="/FavoriteList/AddTitle?id=@item.Id&currentPage=@Context.Request.HttpContext.Request.Path&searchitem = @ViewBag.Search">В избранное</a>
                                    </button>
                                }
                            </div>

                        </div>
                    </div>
                }
            }
        </div>
    }
        <!-- Если по данному запросу нет результата то отображается этот заголовок -->
    <!-- else {
    <h1>Пустая строка поиска</h1>
    } -->
</div>