LibraryRequiem/Controllers/AccountsController.cs
using LibraryRequiem.Data;
using LibraryRequiem.Helpers;
using LibraryRequiem.Models;
using LibraryRequiem.Models.ViewModel;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;

namespace LibraryRequiem.Controllers
{
    public class AccountsController : Controller
    {

        private readonly CollectionContext _context;
        private readonly IWebHostEnvironment _environment;

        public AccountsController(CollectionContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        public ActionResult Register()
        {
            return PartialView();
        }

        // POST: AccountController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Register([FromBody] RegisterViewModel? model)
        {
            // Проверка модели на валидность
            if (ModelState.IsValid)
            {
                // Поиск пользователя с указанным именем в базе данных
                var user = await _context.Users.FirstOrDefaultAsync(x => x.UserName == model.UserName);

                // Если пользователь с таким именем уже существует, добавляем ошибку в модель
                if (user != null)
                {
                    ModelState.AddModelError("", "Пользователь с данным именем уже существует!!!");
                    return BadRequest(ModelState);
                }

                // Создание нового пользователя
                user = new UserModel
                {
                    // Имя пользователя
                    UserName = model.UserName,

                    // Роль пользователя
                    Role = "",

                    // Зашифрованный пароль
                    Password = HashPasswordHelper.HashPassword(model.Password)
                };        
                
                // Добавление нового пользователя в контекст базы данных
                _context.Users.Add(user);

                // Сохранение изменений в базе данных
                await _context.SaveChangesAsync();

                // Аутентификация пользователя
                var result = AccountService.Authenticate(user);

                // Попытка авторизации пользователя
                try
                {
                    // Авторизация пользователя с использованием схемы аутентификации по куки
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(result));

                    // Создание списка избранных книг для пользователя
                    user.FavoriteList = new FavoriteListModel()
                    {
                        Books = new List<FavoriteBookModel>(),

                        User = user,

                        UserId = user.Id,
                    };

                    // Создание профиля пользователя
                    user.Profile = new ProfileModel()
                    {
                        UserId = user.Id,

                        User = user,

                        // Установка иконки профиля по умолчанию
                        AccountIcon = System.IO.File.ReadAllBytes(_environment.WebRootPath + "/images/Defaulticon.png")
                    };

                    // Обновление данных пользователя в контексте базы данных
                    _context.Users.Update(user);

                    // Сохранение изменений в базе данных
                    await _context.SaveChangesAsync();

                    // Перенаправление на главную страницу
                    return RedirectToAction("Index", "Home");
                }
                catch
                {
                    // Добавление ошибки в модель в случае возникновения исключения
                    ModelState.AddModelError("", "Внутренняя ошибка");
                }

            }
            return BadRequest(ModelState);
        }

        public ActionResult Login()
        {
            // Отображение частичного представления формы входа
            return PartialView();
        }

        // POST: AccountController/Edit/5
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<ActionResult> Login([FromBody] LoginViewModel LoginView) {
            // Проверка модели на валидность
            if (ModelState.IsValid)
            {
                // Попытка входа в систему с использованием сервиса аутентификации
                var result = new AccountService(_context).Login(LoginView);

                // Если вход в систему не удался, добавляем ошибку в модель
                if (result == null)
                {
                    ModelState.AddModelError("", "Неверный логин или пароль");

                    // Возвращаем частичное представление формы входа
                    return BadRequest(ModelState);
                }

                // Авторизация пользователя с использованием схемы аутентификации по кукам
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(result));

                // Перенаправление на главную страницу
                return RedirectToAction("Index", "Home");
            }

            ModelState.AddModelError("", "Ошибка при заполнении данных");

            // Возвращаем частичное представление формы входа в случае невалидной модели
            return BadRequest(ModelState );
        }

        public ActionResult Logout(int id)
        {
            // Проверка того, что пользователь авторизован
            if (User.Identity.Name != null)
            {
                // Выход из системы с использованием схемы аутентификации по кукам
                HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

                // Перенаправление на главную страницу
                return RedirectToAction("Index", "Home");
            }

            // Возвращение представления выхода из системы в случае, если пользователь не авторизован
            return View();
        }
    }
}

LibraryRequiem/Controllers/ProfileController.cs
using LibraryRequiem.Data;
using LibraryRequiem.Models;
using LibraryRequiem.Models.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace LibraryRequiem.Controllers
{
    public class ProfileController : Controller
{
    private readonly CollectionContext _context;

    public ProfileController(CollectionContext context)
    {
        _context = context;
    }

    public async Task<IActionResult> Index()
        {
            // Получение модели пользователя из базы данных, включая связанные сущности "Профиль" и "Список избранных книг"
            var userModel = await _context.Users.Include(x => x.Profile)
                .Include(x => x.FavoriteList.Books)
                .FirstOrDefaultAsync(x => x.UserName == User.Identity.Name);

            // Получение всех книг из базы данных
            var books = _context.Books;

            // Список моделей книг для избранных книг
            List<BookModel> favoriteBooks = new List<BookModel>();

            // Перебор избранных книг пользователя
            foreach (var favoritebook in userModel.FavoriteList.Books)
                {
                    // Получение книги из базы данных по идентификатору из избранного
                    var chosenBook = await books.FirstOrDefaultAsync(x => x.Id == favoritebook.BookId);
                    favoriteBooks.Add(chosenBook);
                }

            // Создание модели представления профиля
            var model = new ProfileViewModel
                {
                    // Имя пользователя
                    ProfileName = User.Identity.Name,

                    // Изображение профиля в виде base64-строки
                    ProfileIcon = "data:image/png;base64, " + Convert.ToBase64String(userModel.Profile.AccountIcon),

                    // Список избранных книг
                    Books = favoriteBooks
                };

            // Возврат представления профиля с моделью
            return View(model);
        }
    }
}

LibraryRequiem/Views/Shared/_Layout.cshtml
<!-- Объявление типа документа, указывает браузеру на использование стандарта HTML5 -->
<!DOCTYPE html>
<!-- Открывающий тег html, атрибут 'lang' указывает основной язык документа русский -->
<html lang="ru">
<head>
    <!-- Устанавливаем кодировку для контента страницы -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- Задаем название страницы, "Title" будет заменен на значение из ViewData -->
    <title>@ViewData["Title"]</title>
    <!-- Подключаем минифицированную версию Bootstrap для стилей -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <!-- Подключаем файл стилей site.css для кастомизации дизайна страницы -->
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <!-- Подключаем файл стилей LibraryRequiem.styles.css для кастомизации дизайна страницы; используем версионирование для кэширования -->
    <link rel="stylesheet" href="~/LibraryRequiem.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/ModalLogin.css" asp-append-version="true"/>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js"></script>
</head>
<body>
    <!-- Шапка сайта, содержит навигационное меню -->
    <header>
        <forAjax>

        </forAjax>
        <!-- Основная навигационная панель -->
        <nav class="navbar">
            <!-- Контейнер для логотипа -->
            <div class="logo">
                <!-- Ссылка на главную страницу с изображением логотипа -->
                <a class="logo" asp-controller="home" asp-action="index"><img src="~/images/Livsi_logo.png"></a>
            </div>
            <ul>
                <!-- Элемент выпадающего списка -->
                <li class="dropdown">
                    <!-- Форма с кнопкой для перехода к коллекции -->
                    <form asp-action="Index" asp-controller="Collection"><button class="href_text">Коллекция</button></form>
                    <!-- Контент выпадающего списка, отображающийся при наведении -->
                    <div class="dropdown-content">
                        <!-- Проверка и итерация по элементам, переданным через ViewBag.Genres -->
                        @if (ViewBag.Genres != null)
                        {
                            @foreach (var item in ViewBag.Genres)
                            {
                                <!-- Форма для отправки жанра коллекции методом POST -->
                                <form method="post" asp-action="SearchResult" asp-controller="Collection">
                                    <input class="input" type="submit" name="searchGenre" value="@item" />
                                </form>
                            }
                        }
                    </div>
                </li>
            </ul>

            <div class="right-header">
                <!-- Форма поиска -->
                <form method="post" asp-controller="Collection" asp-action="SearchResult">
                    <div class="search">
                        <input value="@ViewBag.SearchField" class="search_input" type="text" name="searchitem" placeholder="Найти...">
                        <!-- Кнопка для отправки формы с иконкой поиска -->
                        <button><img src="/images/icons8-google-поиск-50.png" /></button>
                    </div>
                </form>
                @if (!User.Identity.IsAuthenticated)
                {
                    <button class="login_window_button">
                            Войти
                    </button>
                }

                else
                {
                    <button data-modal-button class="list-group-item">
                        <a asp-action="Index" asp-controller="Profile" style="text-decoration:none; color: black">@User.Identity.Name</a>
                    </button>

                    <button data-modal-button class="list-group-item">
                        <a asp-action="Logout" asp-controller="Accounts" style="text-decoration:none; color: black">Выйти</a>
                    </button>
                }
            </div>
        </nav>
    </header>
    <!-- Основной контейнер для содержимого страницы -->
    <div class="container">
        <!-- Главное содержимое страницы, вставленное из других Razor представлений -->
        <main role="main" class="page">
            @RenderBody()
        </main>
        <!-- Подвал сайта с контактной информацией и ссылками на социальные сети-->
        <footer class="footer">
            <div class="footer_content">
                <div class="footer_links">
                    <!-- Ссылки на социальные сети (или другие страницы), используется заглушка asp-action="NotFind" -->
                    <a asp-action="NotFind">
                        <img src="~/images/telegram-logo-png-telegram-logo-png-img-504-504-free-transparent-telegram-900x520.png"/>
                    </a>
                    <a asp-action="NotFind">
                        <img src="~/images/square_83.png"/>
                    </a>
                </div>
                <!-- Логотип и копирайт в подвале сайта -->
                <div class="footer_logo">
                    <p>LivsiLib 2023</p>
                </div>
            </div>
        </footer>
        <!-- Подключение скриптов jQuery, Bootstrap и пользовательских скриптов -->
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <!-- Вставка дополнительных скриптов, определяемых в других представлениях -->
        @await RenderSectionAsync("Scripts", required: false)

        <script>

            $('.login_window_button').on('click', function (e) {
                $.get('/accounts/login', function (data) {
                    $('forAjax').html(data);
                    $('.login_wrapper').addClass('show');
                });
            });

        </script>
    </div>
</body>
</html>